### ISSUE TITLE
BaseURL is ignored

### ISSUE THREAD

**Issue by aliok** [silas/node-jenkins#36]
```javascript
var jenkins = require('jenkins')({baseUrl: '"http://admin:admin@localhost:8080"'});
jenkins.info(function(err, data) {
    if (err) throw err;

    console.log('info', data);
});
```

Output
```bash
Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```

**Comment by aliok** [comment]
Ok, my bad, I had quotes inside the baseUrl.


But still, it might be good to do some validation etc.
