### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by Erliz** [silas/node-jenkins#39]
Hi!
I have jenkins instance with self sign cert.
On attempt to send some request i got an error:
```
{ Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY', res: undefined }
```

In my other service a have request module with opts `options.rejectUnauthorized = false;` which work fine for me.
How to add "ignore bad cert" option in your library?

**Comment by Erliz** [comment]
```Jenkins({
      baseUrl: url,
      rejectUnauthorized: false,
    });```
solve my problem and i add PR #40 for peoples like me.
