### ISSUE TITLE
Issue getting logStream working for lastBuild or current build

### ISSUE THREAD

**Issue by suhasdeshpande** [silas/node-jenkins#45]
```javascript
const jenkins = require('jenkins')({
    baseUrl: 'http://USER_NAME:PASSWORD@localhost:8080',
    crumbIssuer: true,
    promisify: true,
});

async function talkToJenkins() {
    try {
        const buildId = await jenkins.job.build('example-job');
        const stream = await jenkins.build.logStream('example-job', buildId, 'Text');
        stream.on('data', text => {
            process.stdout.write(text);
        });
        stream.on('error', error => {
            console.log('error', error);
        });
        stream.on('end', () => {
            console.log('END');
        });
    } catch (error) {
        console.log(error);
    }
}
```

Running this, I am getting following error,

```javascript
error { Error: jenkins: build.log: example-job 17 not found
    at Jenkins.<anonymous> (/Users/eja772/jenkins-build/node_modules/jenkins/lib/middleware.js:82:17)
    at next (/Users/eja772/jenkins-build/node_modules/papi/lib/client.js:300:10)
    at Jenkins._onResponse (/Users/eja772/jenkins-build/node_modules/jenkins/lib/jenkins.js:138:3)
    at next (/Users/eja772/jenkins-build/node_modules/papi/lib/client.js:300:10)
    at IncomingMessage.<anonymous> (/Users/eja772/jenkins-build/node_modules/papi/lib/client.js:600:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) notFound: true }
END
```

I want to stream logs of the job in progress. Am I not using this correctly?

**Comment by totalpave** [comment]
@suhasdeshpande  I am running into the same issue using both promises and callbacks. The callback appears to be fired too early. If I use a setTimeout to wait a few seconds before trying to get the stream, it works.

Did you find a cleaner solution?

**Comment by silas** [comment]
@totalpave You need to wait on the build ID to be created, you can see an example here: https://github.com/silas/node-jenkins/issues/30#issuecomment-238436339
