### ISSUE TITLE
trigger/get jenkins job details inside the folder

### ISSUE THREAD

**Issue by Saggi432** [silas/node-jenkins#55]
@silas my jenkins job is inside the folder,, https://myjenkins.com/misc/job/SatishM/job/sampleNode-Jenkins/21/ 

This jenkins master is connected to the joc.. and the base url for the master is https://myjenkins.com/misc.. i am able to make the initial connection.. however when i try to call the job inside the folder it fails to recognize the job..

jenkins.build.get('sampleNode-Jenkins', 1, function(err, data) {})

the error is as below..

Error: jenkins: job.get: sampleNode-Jenkins not found
    at Jenkins.<anonymous> (/nas/buildInstallers/node_modules/jenkins/lib/middleware.js:82:17)
    at next (/nas/buildInstallers/node_modules/papi/lib/client.js:300:10)
    at Jenkins._onResponse (/nas/buildInstallers/node_modules/jenkins/lib/jenkins.js:138:3)
    at next (/nas/buildInstallers/node_modules/papi/lib/client.js:300:10)
    at IncomingMessage.<anonymous> (/nas/buildInstallers/node_modules/papi/lib/client.js:600:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by silas** [comment]
You can reference jobs in folders by passing in the folder name with the job name, ex: `SatishM/sampleNode-Jenkins` assuming `sampleNode-Jenkins` was in the top level folder `SatishM`. If have more than 1 folder just add more slashes, ex: `folder1/folder2/myJobName`.
