### ISSUE TITLE
issue with copy method

### ISSUE THREAD

**Issue by ghost** [silas/node-jenkins#7]
Hello,

i am using a your excellent api to create a tool that automaticaly create jobs based on branche in a repository. Everythoing works fine except the fact that all jobs created with the copy() method are not runable in the jenkins interface, there is no play button to launch those jobs and even if the template job had a trigger like scm changes, it still doesnt launch the jobs crated with this method!

I have to disable and enable  the copy (using the api-methods) for it to be runnable, is it something that is expected or maybe i am doing something wrong when updating the configuration?

**Comment by LafonteFull** [comment]
> Copied jobs are disabled by default (by Jenkins, not this library), the reasoning being that the job could possibly conflict with the `from` job.
> 
> Enable not working by default looks like a bug in Jenkins, although I couldn't find it reported in Jira yet, but definitely referenced elsewhere on the internet.
> 
> ```shell
>     # enable the job, there seems to be a bug where we need to first disable and then enable
>     `$CURL -o /dev/null --data disable "$HUDSON_URL/job/$TO_PROJECT/disable"`
>     `$CURL -o /dev/null --data enable "$HUDSON_URL/job/$TO_PROJECT/enable"`
> ```
> 
> [source](https://wiki.jenkins-ci.org/display/JENKINS/Bash+Job+Clone+script)
> 
> This might be the easiest way to get around this:
> 
> ```js
> jenkins.job.config({ name: 'fromJob' }, function(err, xml) {
>   if (err) throw err;
> 
>   jenkins.job.create({ name: 'newJob', xml: xml }, function(err) {
>     if (err) throw err;
>   });
> });
> ```

Hi @silas ,
i got an 'internal server error' while trying to create new job using xml file as you mention above.
what i miss?

Code:
` jenkins.job.create({ name: 'joy', xml: {pathToFile}, function(err) {
    if (err) throw err;
   });
  });`

Error:
`Error: jenkins: job.create: internal server error
    at create (/Users/aryokusumo/gitLab/helperv2/node_modules/papi/lib/errors.js:14:5)
    at Object.response (/Users/aryokusumo/gitLab/helperv2/node_modules/papi/lib/errors.js:38:15)
    at IncomingMessage.<anonymous> (/Users/aryokusumo/gitLab/helperv2/node_modules/papi/lib/client.js:592:26)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`
