### ISSUE TITLE
Trying to initialize jenkins but get Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by aguskianto** [silas/node-jenkins#91]
I am trying to connect to jenkins using:
var jenkins = require('jenkins')({ baseUrl: 'https://user:token@link', crumbIssuer: true });

But, I got:
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  res: undefined
}

![image](https://user-images.githubusercontent.com/5397589/77429208-e130f880-6e0b-11ea-85bd-7348133e141b.png)

As you can see above. One thing for sure: jenkins server is using https. Is there a way to use token? And, does node-jenkins support https?

**Comment by silas** [comment]
node-jenkins uses the global https agent by default, so it will validate any certificate that the default node installation does.

You can 1) ensure that your installation has validate certificates for your node.js installation, 2) add your custom certificate using [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file), or 3) add a custom certificate using the https.request options or disable verification (not recommend): see https://github.com/silas/node-jenkins/issues/13#issuecomment-112406860

I don't know how your certificates were generated or what version of node you're using, but updating to a later version of node might fix it as well.

**Comment by pro-sumer** [comment]
I have the same issue with a self-signed certificate and want to use `rejectUnauthorized` as suggested in #13:

```
const https = require('https')
const agent = new https.Agent()
const jenkins = require('jenkins')({ baseUrl: process.env.JENKINS_BASE_URL, promisify: true, rejectUnauthorized: false, agent: agent })
```

However:
```
node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1498:34)
    at TLSSocket.emit (node:events:376:20)
    at TLSSocket._finishInit (node:_tls_wrap:933:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:707:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

What am I doing wrong?

(I'm not the owner of this Jenkins installation; I cannot change the certificate)
