### ISSUE TITLE
Internal Server Error while trying to Create new Job

### ISSUE THREAD

**Issue by LafonteFull** [silas/node-jenkins#99]
i got an 'internal server error' while trying to create new job using xml file.
what i miss?

```
Code:
jenkins.job.create({ name: 'joy', xml: {pathToFile}, function(err) { if (err) throw err; }); });
```

```
Error: jenkins: job.create: internal server error at create
(/node_modules/papi/lib/errors.js:14:5) at Object.response
(/node_modules/papi/lib/errors.js:38:15) at IncomingMessage.<anonymous>
(/papi/lib/client.js:592:26) at IncomingMessage.emit (events.js:187:15) at >
endReadableNT (_stream_readable.js:1094:12) at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by LafonteFull** [comment]
Hi, Sorry.
I didn't notice that xml mention in create job is not xml file, but xml data.

so i just need to change my code like this and works.
thanks guys.

```
fs.readFile(filePath, function(err, data) {
      if (err) throw err;
      jenkinsLib.job.create({name:'aryo/mr', xml: data}, function(err) {
        if (err) throw err;
        res.send(' created!');
      });
    });
```
